apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        # We advise you to build, push and use your own image, instead of using instructor's image.      
        image: tarunshrma/backend:v1
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 8081
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    sidecar.jaegertracing.io/inject: "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: backend
  labels:
    app: backend
    release: prometheus
  name: backend
  namespace: monitoring
spec:
  endpoints:
    - path: /metrics
      port: backend
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: backend
