apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sidecar.jaegertracing.io/inject: 'true'
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: backendport
  labels:
    # name: backend
    app: backend
    # release: prometheus
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: tarunshrma/backend:v1.1
        ports:
        - name: backendport
          containerPort: 8081
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
spec:
  selector:
    app: backend
  ports:
    - name: backend
      protocol: TCP
      port: 8081
      targetPort: backendport
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  # annotations:
  #   sidecar.jaegertracing.io/inject: "true"
  #   prometheus.io/scrape: "true"
  #   prometheus.io/path: /metrics
  #   prometheus.io/port: backend
  labels:
    app: backend
    release: prometheus
  name: backend
  namespace: monitoring
spec:
  endpoints:
    - path: /metrics
      port: backend
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: backend
