apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sidecar.jaegertracing.io/inject: 'true'
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: frontendport
  labels:
    app: fronend
  name: fronend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: tarunshrma/frontend:v1.1
        ports:
        - name: frontendport
          containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - name: frontend
      protocol: TCP
      port: 8080
      targetPort: frontendport
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  # annotations:
  #   sidecar.jaegertracing.io/inject: "true"
  #   prometheus.io/scrape: "true"
  #   prometheus.io/path: /metrics
  #   prometheus.io/port: frontend
  labels:
    app: frontend
    release: prometheus
  name: frontend
  namespace: monitoring
spec:
  endpoints:
    - path: /metrics
      port: frontend
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: frontend