apiVersion: apps/v1
kind: Deployment
metadata:
  name: trial-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trial
  template:
    metadata:
      labels:
        app: trial
    spec:
      containers:
      - name: trial
        # We advise you to build, push and use your own image, instead of using instructor's image.
        image: ghcr.io/jasonsmithio/trial:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: trial-service
spec:
  selector:
    app: trial
  ports:
    - port: 8082
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    sidecar.jaegertracing.io/inject: "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: trial
  labels:
    app: trial
    release: prometheus
  name: trial
  namespace: monitoring
spec:
  endpoints:
    - path: /metrics
      port: trial
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: trial