{
 "title": "Udacity Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(container) (container_memory_working_set_bytes{namespace=\"default\"})/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Uptime (hours)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max by (container) (time() - container_start_time_seconds{container=\"backend\"}))/3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend Uptime (hours)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max by (container) (time() - container_start_time_seconds{container=\"frontend\"}))/3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(container) (container_cpu_usage_seconds_total{namespace=\"default\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Http Request",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    flask_http_request_duration_seconds_count{status!=\"200\"}[30d]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Http Request",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    flask_http_request_duration_seconds_count{status=\"200\"}[30d]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"200\"}[30s]) / rate(flask_http_request_duration_seconds_count{status=\"200\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "welcome",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "type": "gettingstarted",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latest from the blog",
   "type": "news",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {}
   ]
  }
 ]
}